### ISSUE TITLE
Add Zarr section to data formats

### ISSUE THREAD

**Issue by mgrover1** [ProjectPythia/pythia-foundations#100]
Within the data format section, add a section discussing the [Zarr](https://zarr.readthedocs.io/en/stable/) file format and some use cases

**Comment by brian-rose** [comment]
Any good existing content on this? Drop links here.

**Comment by brian-rose** [comment]
Discussed at the EWG meeting on 2/17/2022. The consensus was that this subject is not "foundational" enough to belong in Foundations, but should appear in a Cookbook that explores different data formats more fully.

Now mentioned over at https://github.com/ProjectPythia/pythia-cookbook/issues/1

I'll close this issue here.
