### ISSUE TITLE
Datasets not recognized in new Xarray content

### ISSUE THREAD

**Issue by r-ford** [ProjectPythia/pythia-foundations#133]
In #107 the two new notebooks are giving the error `File 'CESM2_sst_data.nc' is not in the registry.` My local build works fine and I see the files in `pythia-datasets`, so I am not sure what the problem is. @mgrover1, do you know what might be causing this?

**Comment by mgrover1** [comment]
Ahh I think we will need to add a new release to the [pythia-datasets](https://github.com/ProjectPythia/pythia-datasets) repo, since the PR is likely pulling the older version which does not include the new datasets. @andersy005 would you be able to help with issuing the new release? I can help with this!

**Comment by andersy005** [comment]
@mgrover1, please feel free to cut a new release. The process is automated. All you have to do is make a release on GitHub: https://github.com/ProjectPythia/pythia-datasets/releases and the GitHub action will take care of the rest.

To avoid running into this issue when new datasets are added, it is worth looking into ways to stream the registry file from the GitHub repo (https://github.com/ProjectPythia/pythia-datasets/blob/1dd812d616e835dae50b059b6bb63897d70aa1dc/pythia_datasets/datasets.py#L10) instead of packaging it with the package itself.

**Comment by mgrover1** [comment]
Thanks @andersy005 - that is a good point, and something we should consider. I went ahead and cut a new release, so @r-ford , you should be good to go now. I think you can just try rerunning the various actions, and it should access the most recent release ([`v2021.9.13`](https://github.com/ProjectPythia/pythia-datasets/releases/tag/v2021.9.13))! Let me know if you have any questions.

**Comment by brian-rose** [comment]
Is this fixed with the new release? Close this issue, and/or open a new issue to follow up on @andersy005's suggestion to avoid similar issues in the future?

**Comment by r-ford** [comment]
This issue is fixed. I think we can open a new one for follow up if needed.
