### ISSUE TITLE
Revisions to all GitHub content

### ISSUE THREAD

**Issue by brian-rose** [ProjectPythia/pythia-foundations#214]
In our push to get the Intro to GitHub content created, we may have left some inconsistencies or differences in style among the sections. Once all sections are merged in, the final step should be to read through everything in order and see what needs ironing out.

**Comment by brian-rose** [comment]
We've set a meeting for Friday 2/25/2022 at 4:30 EST / 2:30 MST for a small group discussion (with me, @clyne, @jukent and @ktyle) to plan out the necessary revisions.

**Comment by jukent** [comment]
I am going to work on the branches/PR overlap today.

**Comment by jukent** [comment]
I'm reading through the forking, branching, and PR content more thoroughly to try and synthesize it better, and I think that "GitHub workflows" (currently covered in the PR chapter) should have its own chapter.

**Comment by brian-rose** [comment]
I think that #270 took care of the capitalization issue, but I'll keep an eye out for any other inconsistencies.

**Comment by r-ford** [comment]
I went through all of the material, and here are some comments and suggestions; I'll open a PR soon with the simpler edits.

The first 3 sections look good.

Cloning and Forking a Repository:

- A nitpick, but you don't need to highlight the link if clicking the copy-to-clipboard icon.
- Trying to clone the forked `<user>/github-sandbox.git` after `ProjectPythia/github-sandbox.git` raises an error because they have the same name. We could solve this by having the user delete or rename the first clone or by cloning in another directory.

Configuring your GitHub account:

- In the linked [GitHub PAT creation page](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token), step 8 says to select which permissions to grant the token. I think we should tell the user which to choose, but I'm not really sure myself.

Basic version control with git:

- "...rest of the history!" --> "...rest of the history or just hit `Q` to exit `git log`!"

Git Branches:

- Remove last sentence of intro paragraph, since we already made a git branch in the previous lesson.
- We should note that here the repo has been cloned using SSH, since using HTTPS asks for a username and password, unlike the screenshot. 
- Where did `newbranch` come from?
- The user can follow along until the ["Merging Branches" section](https://foundations.projectpythia.org/foundations/github/git-branches.html#merging-branches), where a hypothetical branchB is introduced. Do we want the user to be able to follow along until the end?

Opening a Pull Request on GitHub:

- "Open a Pull Request" --> "Open pull request" (this is what the button says in the screenshot) 
- Typo: contributoris --> contributors 
- To be clear, do we want users to actually open PRs on `ProjectPythia/github-sandbox`? I did [here](https://github.com/ProjectPythia/github-sandbox/pull/3), but if a lot of people use this tutorial, it could get messy.

GitHub Workflows:

- Similar issue with the 2 cloned repos with the same name
- It seems to me like the material here has already been explained in previous sections, but maybe the repetition is actually fine. 

Contribute to Project Pythia via GitHub:

- Maybe we could walk the user through forking and cloning `pythia-foundations`, but letting them figure it out would probably be a good exercise.

**Comment by jukent** [comment]
Thanks. @r-ford Let me know if you want me to tackle any of these points.

> To be clear, do we want users to actually open PRs on ProjectPythia/github-sandbox? I did https://github.com/ProjectPythia/github-sandbox/pull/3, but if a lot of people use this tutorial, it could get messy.

Yes I believe that is the plan. Every now and then we can go in and close PRs.

**Comment by brian-rose** [comment]
> > To be clear, do we want users to actually open PRs on ProjectPythia/github-sandbox? I did [ProjectPythia/github-sandbox#3](https://github.com/ProjectPythia/github-sandbox/pull/3), but if a lot of people use this tutorial, it could get messy.
> 
> Yes I believe that is the plan. Every now and then we can go in and close PRs.

We can explore some automation for this. I think it's pretty simple to set up a bot to auto-close PRs that have gone stale after a certain amount of time.

**Comment by dopplershift** [comment]
https://github.com/marketplace/stale

**Comment by r-ford** [comment]
With #273 merged, I think the content looks good. I don't think the remaining items in my previous comment need to be addressed unless a user brings up a similar issue.

**Comment by brian-rose** [comment]
I promised to do one last read-through, which I have not done. I'll keep this issue open until I follow through...

**Comment by jukent** [comment]
I think with Lily's recent read through and edits we can close this.
