### ISSUE TITLE
Link checker failing

### ISSUE THREAD

**Issue by jnmorley** [ProjectPythia/pythia-foundations#302]
The link checker action is failling to run successfully. [link to failed action](https://github.com/ProjectPythia/pythia-foundations/actions/runs/2496219845) When I click on most of the links (specifically links to Cartopy resources) flagged as broken they appear to still work. Two other links are flagged as broken both from the xarray computation-masking page. They are [https://www.ncdc.noaa.gov/teleconnections/enso/indicators/sst/](https://www.ncdc.noaa.gov/teleconnections/enso/indicators/sst/ ) and [https://www.ncdc.noaa.gov/monitoring-content/teleconnections/nino-regions.gif]( https://www.ncdc.noaa.gov/monitoring-content/teleconnections/nino-regions.gif). These two links both respond with 502 proxy errors. The action was run twice with the same results.

**Comment by jukent** [comment]
Thanks for pointing this out @jnmorley

**Comment by r-ford** [comment]
Seems like this may now be resolved. [I ran the link checker here.](https://github.com/ProjectPythia/pythia-foundations/runs/7048288897?check_suite_focus=true#step:6:368)

**Comment by brian-rose** [comment]
Yes, the link-checker actions runs nightly and it hasn't been showing any failures recently (e.g. https://github.com/ProjectPythia/pythia-foundations/actions/runs/2562505060)

Usually these kind of failures are due to some temporary server glitches on the remote end (in this case ncdc.noaa.gov).

I'll close this issue now since no action is required from us.
