### ISSUE TITLE
Kernel spec in template.ipynb

### ISSUE THREAD

**Issue by ktyle** [ProjectPythia/pythia-foundations#69]
After running a jupyterbook build on the current main version of Pythia Foundations, I got a warning that the kernel spec that is in template.ipynb was not found:

> jupyter_client.kernelspec.NoSuchKernel: No such kernel named conda-env-pythia-book-dev-py

Currently, the kernelspec is set as follows in template.ipynb:

> "kernelspec": {
   "display_name": "Python [conda env:pythia-book-dev]",
   "language": "python",
   "name": "conda-env-pythia-book-dev-py"

Our other notebooks currently use "python3" for the kernel, and doing so for template.ipynb makes for a warning-free jupyter book build. 

Yet, our instructions mention creating and activating the "pythia-book-dev" environment ...

**Comment by dcamron** [comment]
I meant to clear that out before committing and forgot. Kernelspecs are annoying in this way. We might want to consider some automation or pre-commit steps to clearing out notebook metadata like this. In the mean time I can re-run this in #39  because I'll have to do the same for those notebooks anyway.

**Comment by dcamron** [comment]
This change in #39 was accidentally un-done. Will fix.

**Comment by brian-rose** [comment]
Oops, sorry about that!
